<?php
$data = [
    'title' => 'MINISTRY OF PORTS AND CIVIL AVIATION — ACTION PLAN 2026',
    'sectors' => [
        'aviation' => [
            'AASL' => [
                'institution_name' => 'Airport & Aviation Services (SL) Private Limited',
                'projects' => [
                    // --- AASL NEW PROJECTS (1-54) ---
                    ['serial_no' => '1', 'project_cord' => '6068', 'institution' => 'AASL', 'category' => 'New', 'division' => 'CE (P&D)', 'project_name' => 'Package 1 - Terminal Expansion', 'location' => 'BIA', 'allocation_2026_original' => '5200', 'allocation_2026_revised' => '5200', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '6.20%', 'Q1_Target' => '5.00%', 'Q1_Cum_Target' => '5.00%', 'Q1_Cum_Prog' => '6.20%', 'Q1_Quarterly_Cum' => '6.20%', 'Q1_Overall_Prog_Final' => '124%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '2', 'project_cord' => '6222', 'institution' => 'AASL', 'category' => 'New', 'division' => 'AL&ID', 'project_name' => 'Airport Operational Building at BIA', 'location' => 'BIA', 'allocation_2026_original' => '10', 'allocation_2026_revised' => '400', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '2.00%', 'Q1_Target' => '2.00%', 'Q1_Cum_Target' => '2.00%', 'Q1_Cum_Prog' => '2.00%', 'Q1_Quarterly_Cum' => '2.00%', 'Q1_Overall_Prog_Final' => '100%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '3', 'project_cord' => '6354', 'institution' => 'AASL', 'category' => 'New', 'division' => 'AL&ID', 'project_name' => 'Departure expansion Project - Phase 1', 'location' => 'BIA', 'allocation_2026_original' => '10', 'allocation_2026_revised' => '10', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '0.00%', 'Q1_Target' => '2.00%', 'Q1_Cum_Target' => '2.00%', 'Q1_Cum_Prog' => '0.00%', 'Q1_Quarterly_Cum' => '0.00%', 'Q1_Overall_Prog_Final' => '0%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '4', 'project_cord' => '6353', 'institution' => 'AASL', 'category' => 'New', 'division' => 'CE (Project)', 'project_name' => 'Solid Waste Disposal System at BIA', 'location' => 'BIA', 'allocation_2026_original' => '8360', 'allocation_2026_revised' => '8360', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '0.00%', 'Q1_Target' => '0.00%', 'Q1_Cum_Target' => '0.00%', 'Q1_Cum_Prog' => '0.00%', 'Q1_Quarterly_Cum' => '0.00%', 'Q1_Overall_Prog_Final' => '0%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '5', 'project_cord' => '6422', 'institution' => 'AASL', 'category' => 'New', 'division' => 'CE(Maintenance)', 'project_name' => 'Improvements to outer perimeter road MRIA', 'location' => 'BIA', 'allocation_2026_original' => '1500', 'allocation_2026_revised' => '1500', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '3.00%', 'Q1_Target' => '3.00%', 'Q1_Cum_Target' => '3.00%', 'Q1_Cum_Prog' => '3.00%', 'Q1_Quarterly_Cum' => '3.00%', 'Q1_Overall_Prog_Final' => '100%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '6', 'project_cord' => '6224', 'institution' => 'AASL', 'category' => 'New', 'division' => 'AL&ID', 'project_name' => 'Improvements to Arrival Lobby-stage 1', 'location' => 'BIA', 'allocation_2026_original' => '4320', 'allocation_2026_revised' => '4320', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '0.50%', 'Q1_Target' => '3.00%', 'Q1_Cum_Target' => '3.00%', 'Q1_Cum_Prog' => '0.50%', 'Q1_Quarterly_Cum' => '0.50%', 'Q1_Overall_Prog_Final' => '17%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '7', 'project_cord' => '6215', 'institution' => 'AASL', 'category' => 'New', 'division' => 'CE (P&D)', 'project_name' => 'Re-arrangement of immigration counters BIA', 'location' => 'BIA', 'allocation_2026_original' => '6800', 'allocation_2026_revised' => '6800', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '8.50%', 'Q1_Target' => '10.00%', 'Q1_Cum_Target' => '10.00%', 'Q1_Cum_Prog' => '8.50%', 'Q1_Quarterly_Cum' => '8.50%', 'Q1_Overall_Prog_Final' => '85%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '8', 'project_cord' => '6007', 'institution' => 'AASL', 'category' => 'New', 'division' => 'MEHE', 'project_name' => 'Automated Carousel Tag Readers BIA', 'location' => 'BIA', 'allocation_2026_original' => '700', 'allocation_2026_revised' => '700', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '2.50%', 'Q1_Target' => '2.50%', 'Q1_Cum_Target' => '2.00%', 'Q1_Cum_Prog' => '2.50%', 'Q1_Quarterly_Cum' => '2.50%', 'Q1_Overall_Prog_Final' => '100%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '9', 'project_cord' => '6221', 'institution' => 'AASL', 'category' => 'New', 'division' => 'CE (P&D)', 'project_name' => 'Passenger Terminal Building JIA (Pkg-B)', 'location' => 'BIA', 'allocation_2026_original' => '6350', 'allocation_2026_revised' => '6350', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '8.50%', 'Q1_Target' => '10.00%', 'Q1_Cum_Target' => '10.00%', 'Q1_Cum_Prog' => '8.50%', 'Q1_Quarterly_Cum' => '8.50%', 'Q1_Overall_Prog_Final' => '85%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '10', 'project_cord' => '6048', 'institution' => 'AASL', 'category' => 'New', 'division' => 'E&ANE', 'project_name' => 'UHF Ground Radio System at BIA', 'location' => 'BIA', 'allocation_2026_original' => '10', 'allocation_2026_revised' => '10', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '6.50%', 'Q1_Target' => '6.50%', 'Q1_Cum_Target' => '7.00%', 'Q1_Cum_Prog' => '6.50%', 'Q1_Quarterly_Cum' => '6.50%', 'Q1_Overall_Prog_Final' => '100%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '11', 'project_cord' => '6077-1', 'institution' => 'AASL', 'category' => 'New', 'division' => 'E&ANE', 'project_name' => 'Supply of 4 nos. of MW Links', 'location' => 'BIA', 'allocation_2026_original' => '340', 'allocation_2026_revised' => '340', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '2.50%', 'Q1_Target' => '3.00%', 'Q1_Cum_Target' => '3.00%', 'Q1_Cum_Prog' => '2.50%', 'Q1_Quarterly_Cum' => '2.50%', 'Q1_Overall_Prog_Final' => '83%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '12', 'project_cord' => '1525652', 'institution' => 'AASL', 'category' => 'New', 'division' => 'E&ANE', 'project_name' => 'IP Migration for E&ANE Network', 'location' => 'BIA', 'allocation_2026_original' => '80', 'allocation_2026_revised' => '80', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '0.00%', 'Q1_Target' => '0.00%', 'Q1_Cum_Target' => '0.00%', 'Q1_Cum_Prog' => '0.00%', 'Q1_Quarterly_Cum' => '0.00%', 'Q1_Overall_Prog_Final' => '0%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '13', 'project_cord' => '1916-7', 'institution' => 'AASL', 'category' => 'New', 'division' => 'CE(Maintenance)', 'project_name' => 'New building for workers at Maint. Complex', 'location' => 'BIA', 'allocation_2026_original' => '1200', 'allocation_2026_revised' => '1200', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '2.00%', 'Q1_Target' => '3.00%', 'Q1_Cum_Target' => '3.00%', 'Q1_Cum_Prog' => '2.00%', 'Q1_Quarterly_Cum' => '2.00%', 'Q1_Overall_Prog_Final' => '67%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '14', 'project_cord' => '6183', 'institution' => 'AASL', 'category' => 'New', 'division' => 'EE', 'project_name' => 'Electrical Engineering Operational Build', 'location' => 'BIA', 'allocation_2026_original' => '500', 'allocation_2026_revised' => '500', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '2.00%', 'Q1_Target' => '3.00%', 'Q1_Cum_Target' => '3.00%', 'Q1_Cum_Prog' => '2.00%', 'Q1_Quarterly_Cum' => '2.00%', 'Q1_Overall_Prog_Final' => '67%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '15', 'project_cord' => '1916-8', 'institution' => 'AASL', 'category' => 'New', 'division' => 'MEHE', 'project_name' => 'Sewer Treatment Plant for JIA', 'location' => 'BIA', 'allocation_2026_original' => '1980', 'allocation_2026_revised' => '1980', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '6.50%', 'Q1_Target' => '6.50%', 'Q1_Cum_Target' => '6.50%', 'Q1_Cum_Prog' => '6.50%', 'Q1_Quarterly_Cum' => '6.50%', 'Q1_Overall_Prog_Final' => '100%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '16', 'project_cord' => '5999-1', 'institution' => 'AASL', 'category' => 'New', 'division' => 'E&ANE', 'project_name' => 'Supply of 4 Nos. of HF Air Band Receivers', 'location' => 'BIA', 'allocation_2026_original' => '400', 'allocation_2026_revised' => '400', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '2.50%', 'Q1_Target' => '3.00%', 'Q1_Cum_Target' => '3.00%', 'Q1_Cum_Prog' => '2.50%', 'Q1_Quarterly_Cum' => '2.50%', 'Q1_Overall_Prog_Final' => '83%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '17', 'project_cord' => '5999-1', 'institution' => 'AASL', 'category' => 'New', 'division' => 'E&ANE', 'project_name' => 'HF Antennas for AASL', 'location' => 'BIA', 'allocation_2026_original' => '1400', 'allocation_2026_revised' => '1400', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '0.00%', 'Q1_Target' => '0.00%', 'Q1_Cum_Target' => '0.00%', 'Q1_Cum_Prog' => '0.00%', 'Q1_Quarterly_Cum' => '0.00%', 'Q1_Overall_Prog_Final' => '0%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '18', 'project_cord' => '6435', 'institution' => 'AASL', 'category' => 'New', 'division' => 'MEHE', 'project_name' => 'Fire water main distribution MRIA', 'location' => 'MRIA', 'allocation_2026_original' => '400', 'allocation_2026_revised' => '400', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '0.00%', 'Q1_Target' => '2.00%', 'Q1_Cum_Target' => '2.00%', 'Q1_Cum_Prog' => '0.00%', 'Q1_Quarterly_Cum' => '0.00%', 'Q1_Overall_Prog_Final' => '0%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'Delayed'],
                    ['serial_no' => '19', 'project_cord' => '6424', 'institution' => 'AASL', 'category' => 'New', 'division' => 'MEHE', 'project_name' => 'Refurbishment of Carousel 01 & 03 BIA', 'location' => 'BIA', 'allocation_2026_original' => '400', 'allocation_2026_revised' => '400', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '0.00%', 'Q1_Target' => '0.00%', 'Q1_Cum_Target' => '0.00%', 'Q1_Cum_Prog' => '0.00%', 'Q1_Quarterly_Cum' => '0.00%', 'Q1_Overall_Prog_Final' => '0%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '20', 'project_cord' => '5001-1', 'institution' => 'AASL', 'category' => 'New', 'division' => 'CE (Project)', 'project_name' => 'Security Billet Complex Mattala', 'location' => 'BIA', 'allocation_2026_original' => '1900', 'allocation_2026_revised' => '1900', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '0.00%', 'Q1_Target' => '5.00%', 'Q1_Cum_Target' => '5.00%', 'Q1_Cum_Prog' => '0.00%', 'Q1_Quarterly_Cum' => '0.00%', 'Q1_Overall_Prog_Final' => '0%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'Delayed'],
                    ['serial_no' => '21', 'project_cord' => '6063', 'institution' => 'AASL', 'category' => 'New', 'division' => 'MEHE', 'project_name' => 'Status Monitoring for Terminal AC', 'location' => 'BIA', 'allocation_2026_original' => '157.50', 'allocation_2026_revised' => '157.50', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '2.50%', 'Q1_Target' => '4.00%', 'Q1_Cum_Target' => '4.00%', 'Q1_Cum_Prog' => '2.50%', 'Q1_Quarterly_Cum' => '2.50%', 'Q1_Overall_Prog_Final' => '63%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '22', 'project_cord' => '5776', 'institution' => 'AASL', 'category' => 'New', 'division' => 'EE', 'project_name' => 'Flood Lighting Apron B1 & D with LED', 'location' => 'JIA', 'allocation_2026_original' => '1250', 'allocation_2026_revised' => '1250', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '2.00%', 'Q1_Target' => '3.00%', 'Q1_Cum_Target' => '3.00%', 'Q1_Cum_Prog' => '2.00%', 'Q1_Quarterly_Cum' => '2.00%', 'Q1_Overall_Prog_Final' => '67%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '23', 'project_cord' => '6356', 'institution' => 'AASL', 'category' => 'New', 'division' => 'MEHE', 'project_name' => 'Refurbishment of Moving Walks', 'location' => 'CIAR', 'allocation_2026_original' => '320', 'allocation_2026_revised' => '320', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '3.00%', 'Q1_Target' => '3.00%', 'Q1_Cum_Target' => '3.00%', 'Q1_Cum_Prog' => '3.00%', 'Q1_Quarterly_Cum' => '3.00%', 'Q1_Overall_Prog_Final' => '100%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '24', 'project_cord' => '6196', 'institution' => 'AASL', 'category' => 'New', 'division' => 'S&FRS', 'project_name' => 'Fire Station & Fire watch Tower - JIA', 'location' => 'BIA', 'allocation_2026_original' => '300', 'allocation_2026_revised' => '300', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '2.00%', 'Q1_Target' => '3.00%', 'Q1_Cum_Target' => '3.00%', 'Q1_Cum_Prog' => '2.00%', 'Q1_Quarterly_Cum' => '2.00%', 'Q1_Overall_Prog_Final' => '67%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '25', 'project_cord' => '6363', 'institution' => 'AASL', 'category' => 'New', 'division' => 'S&FRS', 'project_name' => 'Refurbishment of Fire Station CIAR', 'location' => 'BIA', 'allocation_2026_original' => '1050', 'allocation_2026_revised' => '1050', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '2.00%', 'Q1_Target' => '3.00%', 'Q1_Cum_Target' => '3.00%', 'Q1_Cum_Prog' => '2.00%', 'Q1_Quarterly_Cum' => '2.00%', 'Q1_Overall_Prog_Final' => '67%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '26', 'project_cord' => '6413', 'institution' => 'AASL', 'category' => 'New', 'division' => 'EE', 'project_name' => 'LV Power Distribution system expansion', 'location' => 'BIA', 'allocation_2026_original' => '1050', 'allocation_2026_revised' => '1050', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '0.00%', 'Q1_Target' => '0.00%', 'Q1_Cum_Target' => '0.00%', 'Q1_Cum_Prog' => '0.00%', 'Q1_Quarterly_Cum' => '0.00%', 'Q1_Overall_Prog_Final' => '0%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '27', 'project_cord' => '6195', 'institution' => 'AASL', 'category' => 'New', 'division' => 'S&FRS', 'project_name' => 'Fire Sub Station at 04 End of BIA', 'location' => 'BIA', 'allocation_2026_original' => '350', 'allocation_2026_revised' => '350', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '2.00%', 'Q1_Target' => '3.00%', 'Q1_Cum_Target' => '3.00%', 'Q1_Cum_Prog' => '2.00%', 'Q1_Quarterly_Cum' => '2.00%', 'Q1_Overall_Prog_Final' => '67%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '28', 'project_cord' => '6182', 'institution' => 'AASL', 'category' => 'New', 'division' => 'EE', 'project_name' => 'AGL Substation Expansion Project', 'location' => 'BIA', 'allocation_2026_original' => '800', 'allocation_2026_revised' => '800', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '8.00%', 'Q1_Target' => '10.00%', 'Q1_Cum_Target' => '10.00%', 'Q1_Cum_Prog' => '8.00%', 'Q1_Quarterly_Cum' => '8.00%', 'Q1_Overall_Prog_Final' => '80%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '29', 'project_cord' => '6432', 'institution' => 'AASL', 'category' => 'New', 'division' => 'HR', 'project_name' => 'Renovation of House No. 01, 02 MRIA', 'location' => 'MRIA', 'allocation_2026_original' => '1040', 'allocation_2026_revised' => '1040', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '1.00%', 'Q1_Target' => '5.00%', 'Q1_Cum_Target' => '5.00%', 'Q1_Cum_Prog' => '1.00%', 'Q1_Quarterly_Cum' => '1.00%', 'Q1_Overall_Prog_Final' => '20%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'Delayed'],
                    ['serial_no' => '30', 'project_cord' => '6228', 'institution' => 'AASL', 'category' => 'New', 'division' => 'AM', 'project_name' => 'Electrical hanging fence MRIA', 'location' => 'BIA', 'allocation_2026_original' => '1000', 'allocation_2026_revised' => '1000', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '1.00%', 'Q1_Target' => '5.00%', 'Q1_Cum_Target' => '5.00%', 'Q1_Cum_Prog' => '1.00%', 'Q1_Quarterly_Cum' => '1.00%', 'Q1_Overall_Prog_Final' => '20%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'Delayed'],
                    ['serial_no' => '31', 'project_cord' => '6428', 'institution' => 'AASL', 'category' => 'New', 'division' => 'HR', 'project_name' => 'Existing SLAF Buildings staff accommodation', 'location' => 'JIA', 'allocation_2026_original' => '1000', 'allocation_2026_revised' => '1000', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '0.00%', 'Q1_Target' => '2.50%', 'Q1_Cum_Target' => '2.50%', 'Q1_Cum_Prog' => '0.00%', 'Q1_Quarterly_Cum' => '0.00%', 'Q1_Overall_Prog_Final' => '0%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'Delayed'],
                    ['serial_no' => '32', 'project_cord' => '5939', 'institution' => 'AASL', 'category' => 'New', 'division' => 'E&ANE', 'project_name' => 'Passenger Screening Equipment AASL', 'location' => 'BIA', 'allocation_2026_original' => '900', 'allocation_2026_revised' => '900', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '18.50%', 'Q1_Target' => '10.00%', 'Q1_Cum_Target' => '10.00%', 'Q1_Cum_Prog' => '18.50%', 'Q1_Quarterly_Cum' => '18.50%', 'Q1_Overall_Prog_Final' => '85%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'Delayed'],
                    ['serial_no' => '33', 'project_cord' => '6071', 'institution' => 'AASL', 'category' => 'New', 'division' => 'MEHE', 'project_name' => 'Water Treatment Plant for JIA', 'location' => 'BIA', 'allocation_2026_original' => '900', 'allocation_2026_revised' => '900', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '6.50%', 'Q1_Target' => '6.50%', 'Q1_Cum_Target' => '6.50%', 'Q1_Cum_Prog' => '6.50%', 'Q1_Quarterly_Cum' => '6.50%', 'Q1_Overall_Prog_Final' => '100%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '34', 'project_cord' => '6360', 'institution' => 'AASL', 'category' => 'New', 'division' => 'IT', 'project_name' => 'Weighing Scales at Check-in counters', 'location' => 'BIA', 'allocation_2026_original' => '600', 'allocation_2026_revised' => '600', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '2.00%', 'Q1_Target' => '3.00%', 'Q1_Cum_Target' => '3.00%', 'Q1_Cum_Prog' => '2.00%', 'Q1_Quarterly_Cum' => '2.00%', 'Q1_Overall_Prog_Final' => '67%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '35', 'project_cord' => '6003', 'institution' => 'AASL', 'category' => 'New', 'division' => 'IT', 'project_name' => 'Database Replication Server and DR', 'location' => 'BIA', 'allocation_2026_original' => '85.50', 'allocation_2026_revised' => '85.50', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '6.50%', 'Q1_Target' => '10.00%', 'Q1_Cum_Target' => '10.00%', 'Q1_Cum_Prog' => '6.50%', 'Q1_Quarterly_Cum' => '6.50%', 'Q1_Overall_Prog_Final' => '65%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'Delayed'],
                    ['serial_no' => '36', 'project_cord' => '6172', 'institution' => 'AASL', 'category' => 'New', 'division' => 'SLAA', 'project_name' => 'AAA BIA Branch - JAC Building', 'location' => 'BIA', 'allocation_2026_original' => '950', 'allocation_2026_revised' => '950', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '2.00%', 'Q1_Target' => '5.00%', 'Q1_Cum_Target' => '5.00%', 'Q1_Cum_Prog' => '2.00%', 'Q1_Quarterly_Cum' => '2.00%', 'Q1_Overall_Prog_Final' => '40%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'Delayed'],
                    ['serial_no' => '37', 'project_cord' => '6309', 'institution' => 'AASL', 'category' => 'New', 'division' => 'MEHE', 'project_name' => 'Replacement of Chiller No 3 Cargo T5', 'location' => 'BIA', 'allocation_2026_original' => '76.50', 'allocation_2026_revised' => '76.50', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '8.00%', 'Q1_Target' => '10.00%', 'Q1_Cum_Target' => '10.00%', 'Q1_Cum_Prog' => '8.00%', 'Q1_Quarterly_Cum' => '8.00%', 'Q1_Overall_Prog_Final' => '80%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '38', 'project_cord' => '6361', 'institution' => 'AASL', 'category' => 'New', 'division' => 'IT', 'project_name' => 'Gigabit Passive Optical Network BIA', 'location' => 'BIA', 'allocation_2026_original' => '720', 'allocation_2026_revised' => '720', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '2.00%', 'Q1_Target' => '3.00%', 'Q1_Cum_Target' => '3.00%', 'Q1_Cum_Prog' => '2.00%', 'Q1_Quarterly_Cum' => '2.00%', 'Q1_Overall_Prog_Final' => '67%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '39', 'project_cord' => '6167', 'institution' => 'AASL', 'category' => 'New', 'division' => 'AM', 'project_name' => 'Terminal car park wash room refurbishment', 'location' => 'BIA', 'allocation_2026_original' => '800', 'allocation_2026_revised' => '800', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '0.00%', 'Q1_Target' => '3.00%', 'Q1_Cum_Target' => '3.00%', 'Q1_Cum_Prog' => '0.00%', 'Q1_Quarterly_Cum' => '0.00%', 'Q1_Overall_Prog_Final' => '0%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'Delayed'],
                    ['serial_no' => '40', 'project_cord' => '6184', 'institution' => 'AASL', 'category' => 'New', 'division' => 'EE', 'project_name' => 'Supply 1000 kVA Generator PTB BIA', 'location' => 'BIA', 'allocation_2026_original' => '400', 'allocation_2026_revised' => '400', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '2.50%', 'Q1_Target' => '5.00%', 'Q1_Cum_Target' => '5.00%', 'Q1_Cum_Prog' => '2.50%', 'Q1_Quarterly_Cum' => '2.50%', 'Q1_Overall_Prog_Final' => '50%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '41', 'project_cord' => '6370', 'institution' => 'AASL', 'category' => 'New', 'division' => 'CE (P&D)', 'project_name' => 'Car Park near BIA Police Station II', 'location' => 'BIA', 'allocation_2026_original' => '720', 'allocation_2026_revised' => '720', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '3.00%', 'Q1_Target' => '6.00%', 'Q1_Cum_Target' => '6.00%', 'Q1_Cum_Prog' => '3.00%', 'Q1_Quarterly_Cum' => '3.00%', 'Q1_Overall_Prog_Final' => '50%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '42', 'project_cord' => '6204', 'institution' => 'AASL', 'category' => 'New', 'division' => 'IT', 'project_name' => 'Commissioning of NW Distribution System', 'location' => 'BIA', 'allocation_2026_original' => '720', 'allocation_2026_revised' => '720', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '5.00%', 'Q1_Target' => '10.00%', 'Q1_Cum_Target' => '10.00%', 'Q1_Cum_Prog' => '5.00%', 'Q1_Quarterly_Cum' => '5.00%', 'Q1_Overall_Prog_Final' => '50%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'Delayed'],
                    ['serial_no' => '43', 'project_cord' => '6059', 'institution' => 'AASL', 'category' => 'New', 'division' => 'IT', 'project_name' => 'BIA Perimeter Firewall', 'location' => 'MRIA', 'allocation_2026_original' => '67.50', 'allocation_2026_revised' => '67.50', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '8.00%', 'Q1_Target' => '10.00%', 'Q1_Cum_Target' => '10.00%', 'Q1_Cum_Prog' => '8.00%', 'Q1_Quarterly_Cum' => '8.00%', 'Q1_Overall_Prog_Final' => '80%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'Delayed'],
                    ['serial_no' => '44', 'project_cord' => '6170', 'institution' => 'AASL', 'category' => 'New', 'division' => 'AM', 'project_name' => 'Umbrella car park motorcycle shelter', 'location' => 'BIA', 'allocation_2026_original' => '750', 'allocation_2026_revised' => '750', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '0.00%', 'Q1_Target' => '5.00%', 'Q1_Cum_Target' => '5.00%', 'Q1_Cum_Prog' => '0.00%', 'Q1_Quarterly_Cum' => '0.00%', 'Q1_Overall_Prog_Final' => '0%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'Delayed'],
                    ['serial_no' => '45', 'project_cord' => '5894', 'institution' => 'AASL', 'category' => 'New', 'division' => 'E&ANE', 'project_name' => 'Communication Link Building BIA', 'location' => 'BIA', 'allocation_2026_original' => '500', 'allocation_2026_revised' => '500', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '2.00%', 'Q1_Target' => '5.00%', 'Q1_Cum_Target' => '5.00%', 'Q1_Cum_Prog' => '2.00%', 'Q1_Quarterly_Cum' => '2.00%', 'Q1_Overall_Prog_Final' => '40%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '46', 'project_cord' => '6362', 'institution' => 'AASL', 'category' => 'New', 'division' => 'IT', 'project_name' => 'Core Network Upgrade', 'location' => 'BIA', 'allocation_2026_original' => '450', 'allocation_2026_revised' => '450', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '2.00%', 'Q1_Target' => '2.50%', 'Q1_Cum_Target' => '3.00%', 'Q1_Cum_Prog' => '2.00%', 'Q1_Quarterly_Cum' => '2.00%', 'Q1_Overall_Prog_Final' => '80%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '47', 'project_cord' => '6175', 'institution' => 'AASL', 'category' => 'New', 'division' => 'CE(Maintenance)', 'project_name' => 'Asphalt overlaying of apron service road', 'location' => 'BIA', 'allocation_2026_original' => '500', 'allocation_2026_revised' => '500', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '8.50%', 'Q1_Target' => '10.00%', 'Q1_Cum_Target' => '10.00%', 'Q1_Cum_Prog' => '8.50%', 'Q1_Quarterly_Cum' => '8.50%', 'Q1_Overall_Prog_Final' => '85%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '48', 'project_cord' => '6081', 'institution' => 'AASL', 'category' => 'New', 'division' => 'E&ANE', 'project_name' => 'Procurement of VOIP ED137 Gateway', 'location' => 'BIA', 'allocation_2026_original' => '600', 'allocation_2026_revised' => '600', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '8.50%', 'Q1_Target' => '10.00%', 'Q1_Cum_Target' => '10.00%', 'Q1_Cum_Prog' => '8.50%', 'Q1_Quarterly_Cum' => '8.50%', 'Q1_Overall_Prog_Final' => '85%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '49', 'project_cord' => '5782', 'institution' => 'AASL', 'category' => 'New', 'division' => 'E&ANE', 'project_name' => 'Standalone X-Ray Security Equipment', 'location' => 'BIA', 'allocation_2026_original' => '500', 'allocation_2026_revised' => '500', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '2.50%', 'Q1_Target' => '3.00%', 'Q1_Cum_Target' => '3.00%', 'Q1_Cum_Prog' => '2.50%', 'Q1_Quarterly_Cum' => '2.50%', 'Q1_Overall_Prog_Final' => '83%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '50', 'project_cord' => '6300', 'institution' => 'AASL', 'category' => 'New', 'division' => 'MECH', 'project_name' => 'AHU Refurbishment PTB Pier BIA', 'location' => 'BIA', 'allocation_2026_original' => '46.90', 'allocation_2026_revised' => '46.90', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '0.00%', 'Q1_Target' => '0.00%', 'Q1_Cum_Target' => '0.00%', 'Q1_Cum_Prog' => '0.00%', 'Q1_Quarterly_Cum' => '0.00%', 'Q1_Overall_Prog_Final' => '0%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '51', 'project_cord' => '6250', 'institution' => 'AASL', 'category' => 'New', 'division' => 'CE(Maintenance)', 'project_name' => 'Paint Work Arrival Area Terminal BIA', 'location' => 'BIA', 'allocation_2026_original' => '650', 'allocation_2026_revised' => '650', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '0.00%', 'Q1_Target' => '0.00%', 'Q1_Cum_Target' => '0.00%', 'Q1_Cum_Prog' => '0.00%', 'Q1_Quarterly_Cum' => '0.00%', 'Q1_Overall_Prog_Final' => '0%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '52', 'project_cord' => '6357', 'institution' => 'AASL', 'category' => 'New', 'division' => 'MECH', 'project_name' => '350 ton Chiller installation BIA', 'location' => 'BIA', 'allocation_2026_original' => '160', 'allocation_2026_revised' => '160', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '2.50%', 'Q1_Target' => '2.50%', 'Q1_Cum_Target' => '3.00%', 'Q1_Cum_Prog' => '2.50%', 'Q1_Quarterly_Cum' => '2.50%', 'Q1_Overall_Prog_Final' => '100%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '53', 'project_cord' => '6429', 'institution' => 'AASL', 'category' => 'New', 'division' => 'AM', 'project_name' => 'Arrival baggage belt terminal building JIA', 'location' => 'JIA', 'allocation_2026_original' => '800', 'allocation_2026_revised' => '800', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '0.00%', 'Q1_Target' => '2.00%', 'Q1_Cum_Target' => '2.00%', 'Q1_Cum_Prog' => '0.00%', 'Q1_Quarterly_Cum' => '0.00%', 'Q1_Overall_Prog_Final' => '0%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'Delayed'],
                    ['serial_no' => '54', 'project_cord' => '6434', 'institution' => 'AASL', 'category' => 'New', 'division' => 'AM', 'project_name' => 'Departure baggage belt terminal building JIA', 'location' => 'JIA', 'allocation_2026_original' => '500', 'allocation_2026_revised' => '500', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '0.00%', 'Q1_Target' => '0.00%', 'Q1_Cum_Target' => '0.00%', 'Q1_Cum_Prog' => '0.00%', 'Q1_Quarterly_Cum' => '0.00%', 'Q1_Overall_Prog_Final' => '0%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'Delayed'],

                    // --- AASL CONTINUATION PROJECTS ---
                    ['serial_no' => 'C1', 'project_cord' => '6161', 'institution' => 'AASL', 'category' => 'Continuation', 'division' => 'Project', 'project_name' => 'Airport Facility Complex CIAR', 'location' => 'CIAR', 'allocation_2026_original' => '2200', 'allocation_2026_revised' => '2200', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0.00%', 'q1_fin_target' => '240.01', 'phys_percent' => ['Q1' => '4.00%', 'Q1_Target' => '3.00%', 'Q1_Cum_Target' => '3.00%', 'Q1_Cum_Prog' => '4.00%', 'Q1_Quarterly_Cum' => '4.00%', 'Q1_Overall_Prog_Final' => '133%'], 'actual_exp' => ['Q1' => '48.72'], 'timeline_status' => 'On Track'],
                    ['serial_no' => 'C2', 'project_cord' => '5512', 'institution' => 'AASL', 'category' => 'Continuation', 'division' => 'E&ANE', 'project_name' => 'SSR Radar Piduruthalagala', 'location' => 'CIAR', 'allocation_2026_original' => '385', 'allocation_2026_revised' => '385', 'cum_exp_2025' => '477.38', 'cum_phys_2025' => '61.00%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '1.00%', 'Q1_Target' => '1.00%', 'Q1_Cum_Target' => '62.00%', 'Q1_Cum_Prog' => '62.00%', 'Q1_Quarterly_Cum' => '1.00%', 'Q1_Overall_Prog_Final' => '100%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'Delayed'],
                    ['serial_no' => 'C3', 'project_cord' => '5548', 'institution' => 'AASL', 'category' => 'Continuation', 'division' => 'E&ANE', 'project_name' => 'ILS for Runway 04 at BIA', 'location' => 'BIA', 'allocation_2026_original' => '400', 'allocation_2026_revised' => '400', 'cum_exp_2025' => '245.25', 'cum_phys_2025' => '90.00%', 'q1_fin_target' => '60.74', 'phys_percent' => ['Q1' => '5.00%', 'Q1_Target' => '10.00%', 'Q1_Cum_Target' => '100.00%', 'Q1_Cum_Prog' => '95.00%', 'Q1_Quarterly_Cum' => '5.00%', 'Q1_Overall_Prog_Final' => '95%'], 'actual_exp' => ['Q1' => '60.74'], 'timeline_status' => 'Delayed'],
                    ['serial_no' => 'C4', 'project_cord' => '6067', 'institution' => 'AASL', 'category' => 'Continuation', 'division' => 'Project', 'project_name' => 'Aviation Security Facilities BIA', 'location' => 'BIA', 'allocation_2026_original' => '425', 'allocation_2026_revised' => '425', 'cum_exp_2025' => '49.39', 'cum_phys_2025' => '8.00%', 'q1_fin_target' => '135.38', 'phys_percent' => ['Q1' => '6.00%', 'Q1_Target' => '16.00%', 'Q1_Cum_Target' => '24.00%', 'Q1_Cum_Prog' => '14%', 'Q1_Quarterly_Cum' => '6.00%', 'Q1_Overall_Prog_Final' => '58%'], 'actual_exp' => ['Q1' => '85.99'], 'timeline_status' => 'Delayed'],
                    ['serial_no' => 'C5', 'project_cord' => '6337', 'institution' => 'AASL', 'category' => 'Continuation', 'division' => 'Project', 'project_name' => 'Remodeling check-in & baggage belts BIA', 'location' => 'BIA', 'allocation_2026_original' => '588', 'allocation_2026_revised' => '588', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0.00%', 'q1_fin_target' => '94', 'phys_percent' => ['Q1' => '2.00%', 'Q1_Target' => '40.00%', 'Q1_Cum_Target' => '40.00%', 'Q1_Cum_Prog' => '2.00%', 'Q1_Quarterly_Cum' => '2.00%', 'Q1_Overall_Prog_Final' => '5%'], 'actual_exp' => ['Q1' => '94.00'], 'timeline_status' => 'Delayed'],
                    ['serial_no' => 'C6', 'project_cord' => '6407', 'institution' => 'AASL', 'category' => 'Continuation', 'division' => 'Project', 'project_name' => 'Terminal building JIA (Pkg-A)', 'location' => 'JIA', 'allocation_2026_original' => '335', 'allocation_2026_revised' => '335', 'cum_exp_2025' => '0', 'cum_phys_2025' => '7.00%', 'q1_fin_target' => '55.63', 'phys_percent' => ['Q1' => '33.00%', 'Q1_Target' => '69.00%', 'Q1_Cum_Target' => '76.00%', 'Q1_Cum_Prog' => '40%', 'Q1_Quarterly_Cum' => '33.00%', 'Q1_Overall_Prog_Final' => '53%'], 'actual_exp' => ['Q1' => '55.63'], 'timeline_status' => 'Delayed'],
                    ['serial_no' => 'C7', 'project_cord' => '5777', 'institution' => 'AASL', 'category' => 'Continuation', 'division' => 'CE (P&D)', 'project_name' => 'Master plan for BIA', 'location' => 'BIA', 'allocation_2026_original' => '280', 'allocation_2026_revised' => '280', 'cum_exp_2025' => '0', 'cum_phys_2025' => '25.00%', 'q1_fin_target' => '49.66', 'phys_percent' => ['Q1' => '20.00%', 'Q1_Target' => '50.00%', 'Q1_Cum_Target' => '75.00%', 'Q1_Cum_Prog' => '45.00%', 'Q1_Quarterly_Cum' => '20.00%', 'Q1_Overall_Prog_Final' => '60%'], 'actual_exp' => ['Q1' => '49.66'], 'timeline_status' => 'On Track'],
                    ['serial_no' => 'C8', 'project_cord' => '6042', 'institution' => 'AASL', 'category' => 'Continuation', 'division' => 'Project', 'project_name' => 'Refurbishment Lotus lounge-Stage 1', 'location' => 'BIA', 'allocation_2026_original' => '226', 'allocation_2026_revised' => '226', 'cum_exp_2025' => '89.74', 'cum_phys_2025' => '93.00%', 'q1_fin_target' => '170.54', 'phys_percent' => ['Q1' => '7.00%', 'Q1_Target' => '7.00%', 'Q1_Cum_Target' => '100.00%', 'Q1_Cum_Prog' => '100%', 'Q1_Quarterly_Cum' => '7.00%', 'Q1_Overall_Prog_Final' => '100%'], 'actual_exp' => ['Q1' => '80.80'], 'timeline_status' => 'Completed'],
                    ['serial_no' => 'C9', 'project_cord' => '5616', 'institution' => 'AASL', 'category' => 'Continuation', 'division' => 'E&ANE', 'project_name' => 'Radio links between CIAR & BIA', 'location' => 'BIA', 'allocation_2026_original' => '34', 'allocation_2026_revised' => '34', 'cum_exp_2025' => '25.35', 'cum_phys_2025' => '90.00%', 'q1_fin_target' => '70.43', 'phys_percent' => ['Q1' => '0.00%', 'Q1_Target' => '10.00%', 'Q1_Cum_Target' => '100.00%', 'Q1_Cum_Prog' => '90.00%', 'Q1_Quarterly_Cum' => '0.00%', 'Q1_Overall_Prog_Final' => '90%'], 'actual_exp' => ['Q1' => '45.09'], 'timeline_status' => 'Delayed'],
                    ['serial_no' => 'C10', 'project_cord' => '6066', 'institution' => 'AASL', 'category' => 'Continuation', 'division' => 'Project', 'project_name' => 'Construction of Car Park - Stage 1 BIA', 'location' => 'BIA', 'allocation_2026_original' => '157', 'allocation_2026_revised' => '157', 'cum_exp_2025' => '26.18', 'cum_phys_2025' => '60.00%', 'q1_fin_target' => '44.11', 'phys_percent' => ['Q1' => '25.00%', 'Q1_Target' => '40.00%', 'Q1_Cum_Target' => '100.00%', 'Q1_Cum_Prog' => '85%', 'Q1_Quarterly_Cum' => '25.00%', 'Q1_Overall_Prog_Final' => '85%'], 'actual_exp' => ['Q1' => '17.93'], 'timeline_status' => 'Delayed'],
                    ['serial_no' => 'C11', 'project_cord' => '6209', 'institution' => 'AASL', 'category' => 'Continuation', 'division' => 'IT', 'project_name' => 'PABX System BIA', 'location' => 'BIA', 'allocation_2026_original' => '117', 'allocation_2026_revised' => '117', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0.00%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '40.00%', 'Q1_Target' => '40.00%', 'Q1_Cum_Target' => '40.00%', 'Q1_Cum_Prog' => '40.00%', 'Q1_Quarterly_Cum' => '40.00%', 'Q1_Overall_Prog_Final' => '100%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track'],
                    ['serial_no' => 'C12', 'project_cord' => '6344', 'institution' => 'AASL', 'category' => 'Continuation', 'division' => 'IT', 'project_name' => 'Solar Powered IP Cameras BIA', 'location' => 'BIA', 'allocation_2026_original' => '117', 'allocation_2026_revised' => '117', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0.00%', 'q1_fin_target' => '4.81', 'phys_percent' => ['Q1' => '10.00%', 'Q1_Target' => '20.00%', 'Q1_Cum_Target' => '20.00%', 'Q1_Cum_Prog' => '10%', 'Q1_Quarterly_Cum' => '10.00%', 'Q1_Overall_Prog_Final' => '50%'], 'actual_exp' => ['Q1' => '4.81'], 'timeline_status' => 'On Track'],
                    ['serial_no' => 'C13', 'project_cord' => '6006', 'institution' => 'AASL', 'category' => 'Continuation', 'division' => 'MECH', 'project_name' => 'CAD Model Terminal Building BIA', 'location' => 'BIA', 'allocation_2026_original' => '53', 'allocation_2026_revised' => '53', 'cum_exp_2025' => '52.50', 'cum_phys_2025' => '85.00%', 'q1_fin_target' => '52.5', 'phys_percent' => ['Q1' => '0.00%', 'Q1_Target' => '15.00%', 'Q1_Cum_Target' => '100.00%', 'Q1_Cum_Prog' => '85.00%', 'Q1_Quarterly_Cum' => '0.00%', 'Q1_Overall_Prog_Final' => '85%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'Delayed'],
                    ['serial_no' => 'C14', 'project_cord' => '5652', 'institution' => 'AASL', 'category' => 'Continuation', 'division' => 'Project', 'project_name' => 'Refurbishment of Hanger 2 RMA', 'location' => 'BIA', 'allocation_2026_original' => '92', 'allocation_2026_revised' => '92', 'cum_exp_2025' => '28.57', 'cum_phys_2025' => '80.00%', 'q1_fin_target' => '120.83', 'phys_percent' => ['Q1' => '20.00%', 'Q1_Target' => '20.00%', 'Q1_Cum_Target' => '100.00%', 'Q1_Cum_Prog' => '100%', 'Q1_Quarterly_Cum' => '20.00%', 'Q1_Overall_Prog_Final' => '100%'], 'actual_exp' => ['Q1' => '32.18'], 'timeline_status' => 'Completed'],
                    ['serial_no' => 'C15', 'project_cord' => '5940', 'institution' => 'AASL', 'category' => 'Continuation', 'division' => 'IT', 'project_name' => 'Explosive Trace Detectors (ETD)', 'location' => 'BIA', 'allocation_2026_original' => '90', 'allocation_2026_revised' => '90', 'cum_exp_2025' => '0', 'cum_phys_2025' => '60.00%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '20%', 'Q1_Target' => '40.00%', 'Q1_Cum_Target' => '100.00%', 'Q1_Cum_Prog' => '80.00%', 'Q1_Quarterly_Cum' => '20%', 'Q1_Overall_Prog_Final' => '80%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'Delayed'],
                    ['serial_no' => 'C16', 'project_cord' => '6202', 'institution' => 'AASL', 'category' => 'Continuation', 'division' => 'IT', 'project_name' => 'Deployment of DC Replication', 'location' => 'BIA', 'allocation_2026_original' => '77', 'allocation_2026_revised' => '77', 'cum_exp_2025' => '0', 'cum_phys_2025' => '8.50%', 'q1_fin_target' => '85', 'phys_percent' => ['Q1' => '0.00%', 'Q1_Target' => '1.50%', 'Q1_Cum_Target' => '10.00%', 'Q1_Cum_Prog' => '9%', 'Q1_Quarterly_Cum' => '0.00%', 'Q1_Overall_Prog_Final' => '85%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'Delayed'],
                    ['serial_no' => 'C17', 'project_cord' => '6206', 'institution' => 'AASL', 'category' => 'Continuation', 'division' => 'IT', 'project_name' => 'Installation of DC Servers', 'location' => 'BIA', 'allocation_2026_original' => '63', 'allocation_2026_revised' => '63', 'cum_exp_2025' => '0', 'cum_phys_2025' => '10.00%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '0.00%', 'Q1_Target' => '90.00%', 'Q1_Cum_Target' => '100.00%', 'Q1_Cum_Prog' => '10%', 'Q1_Quarterly_Cum' => '0.00%', 'Q1_Overall_Prog_Final' => '10%'], 'actual_exp' => ['Q1' => '1.71'], 'timeline_status' => 'Delayed'],
                    ['serial_no' => 'C18', 'project_cord' => '6002', 'institution' => 'AASL', 'category' => 'Continuation', 'division' => 'EE', 'project_name' => 'Medium Voltage system at BIA', 'location' => 'BIA', 'allocation_2026_original' => '106', 'allocation_2026_revised' => '106', 'cum_exp_2025' => '81.95', 'cum_phys_2025' => '0.00%', 'q1_fin_target' => '81.95', 'phys_percent' => ['Q1' => '15.00%', 'Q1_Target' => '15.00%', 'Q1_Cum_Target' => '15.00%', 'Q1_Cum_Prog' => '15%', 'Q1_Quarterly_Cum' => '15.00%', 'Q1_Overall_Prog_Final' => '100%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track'],
                    ['serial_no' => 'C19', 'project_cord' => '5608', 'institution' => 'AASL', 'category' => 'Continuation', 'division' => 'EE', 'project_name' => '1300kWp Solar System (Scattered)', 'location' => 'BIA', 'allocation_2026_original' => '5', 'allocation_2026_revised' => '5', 'cum_exp_2025' => '53.30', 'cum_phys_2025' => '0.00%', 'q1_fin_target' => '54.30', 'phys_percent' => ['Q1' => '50.00%', 'Q1_Target' => '50.00%', 'Q1_Cum_Target' => '50.00%', 'Q1_Cum_Prog' => '50.00%', 'Q1_Quarterly_Cum' => '50.00%', 'Q1_Overall_Prog_Final' => '100%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track'],
                ]
            ],
            'CAASL' => [
                'institution_name' => 'Civil Aviation Authority of Sri Lanka',
                'projects' => [
                    // --- CAASL PROJECTS ---
                    ['serial_no' => '1', 'project_cord' => 'DGCA& CEO', 'institution' => 'CAASL', 'category' => 'New', 'division' => 'Direction & Management', 'project_name' => 'STRENGTHING AND REGULARIZING THE ACTIVITIES OF BOARD SECRETARIAT', 'location' => 'CAASL', 'allocation_2026_original' => '16.59', 'allocation_2026_revised' => '16.59', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '4.15', 'phys_percent' => ['Q1' => '25%', 'Q1_Target' => '25%', 'Q1_Cum_Target' => '25%', 'Q1_Cum_Prog' => '25%', 'Q1_Quarterly_Cum' => '25%', 'Q1_Overall_Prog_Final' => '100%'], 'actual_exp' => ['Q1' => '2.59'], 'timeline_status' => 'Completed'],
                    ['serial_no' => '2', 'project_cord' => 'DGCA& CEO', 'institution' => 'CAASL', 'category' => 'New', 'division' => 'Direction & Management', 'project_name' => 'STRENGTHING AND REGULARIZING THE ACTIVITIES OF DIRECTOR GENERAL AND CHIEF EXECUTIVE OFFICER\'S OFFICE', 'location' => 'CAASL', 'allocation_2026_original' => '21.79', 'allocation_2026_revised' => '21.79', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '5.45', 'phys_percent' => ['Q1' => '25%', 'Q1_Target' => '25%', 'Q1_Cum_Target' => '25%', 'Q1_Cum_Prog' => '25%', 'Q1_Quarterly_Cum' => '25%', 'Q1_Overall_Prog_Final' => '100%'], 'actual_exp' => ['Q1' => '4.99'], 'timeline_status' => 'Completed'],
                    ['serial_no' => '3', 'project_cord' => 'DGCA& CEO', 'institution' => 'CAASL', 'category' => 'New', 'division' => 'Direction & Management', 'project_name' => 'STRENGTHING AND REGULARIZING THE ACTIVITIES OF ENVIRONMENT, RESEARCH AND PROJECTS SECTION', 'location' => 'CAASL', 'allocation_2026_original' => '37.97', 'allocation_2026_revised' => '37.97', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '9.49', 'phys_percent' => ['Q1' => '25%', 'Q1_Target' => '25%', 'Q1_Cum_Target' => '25%', 'Q1_Cum_Prog' => '25%', 'Q1_Quarterly_Cum' => '25%', 'Q1_Overall_Prog_Final' => '100%'], 'actual_exp' => ['Q1' => '6.24'], 'timeline_status' => 'Completed'],
                    ['serial_no' => '4', 'project_cord' => 'DGCA& CEO', 'institution' => 'CAASL', 'category' => 'New', 'division' => 'Direction & Management', 'project_name' => 'STRENGTHING AND REGULARIZING THE ACTIVITIES OF QUALITY AND INTERNAL AUDIT', 'location' => 'CAASL', 'allocation_2026_original' => '17.32', 'allocation_2026_revised' => '17.32', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '4.33', 'phys_percent' => ['Q1' => '25%', 'Q1_Target' => '25%', 'Q1_Cum_Target' => '25%', 'Q1_Cum_Prog' => '25%', 'Q1_Quarterly_Cum' => '25%', 'Q1_Overall_Prog_Final' => '100%'], 'actual_exp' => ['Q1' => '3.16'], 'timeline_status' => 'Completed'],
                    ['serial_no' => '5', 'project_cord' => 'DGCA& CEO', 'institution' => 'CAASL', 'category' => 'New', 'division' => 'Direction & Management', 'project_name' => 'STRENGTHING AND REGULARIZING THE ACTIVITIES OF LEGAL AFFAIRS AND ENFORCEMENT', 'location' => 'CAASL', 'allocation_2026_original' => '8.33', 'allocation_2026_revised' => '8.33', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '2.08', 'phys_percent' => ['Q1' => '25%', 'Q1_Target' => '25%', 'Q1_Cum_Target' => '25%', 'Q1_Cum_Prog' => '25%', 'Q1_Quarterly_Cum' => '25%', 'Q1_Overall_Prog_Final' => '100%'], 'actual_exp' => ['Q1' => '0.99'], 'timeline_status' => 'Completed'],
                    ['serial_no' => '6', 'project_cord' => 'DGCA& CEO', 'institution' => 'CAASL', 'category' => 'New', 'division' => 'Direction & Management', 'project_name' => 'STRENGTHEN AND REGULARIZING THE ACTIVITIES OF AEROMEDICAL SERVICES', 'location' => 'CAASL', 'allocation_2026_original' => '17.53', 'allocation_2026_revised' => '17.53', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '4.38', 'phys_percent' => ['Q1' => '25%', 'Q1_Target' => '25%', 'Q1_Cum_Target' => '25%', 'Q1_Cum_Prog' => '25%', 'Q1_Quarterly_Cum' => '25%', 'Q1_Overall_Prog_Final' => '100%'], 'actual_exp' => ['Q1' => '3.24'], 'timeline_status' => 'Completed'],
                    ['serial_no' => '7', 'project_cord' => 'DGCA& CEO', 'institution' => 'CAASL', 'category' => 'New', 'division' => 'Direction & Management', 'project_name' => 'STRENGTHING AND REGULARIZING THE ACTIVITIES OF AVIATION SAFETY MONITORING', 'location' => 'CAASL', 'allocation_2026_original' => '9.7', 'allocation_2026_revised' => '9.7', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '2.43', 'phys_percent' => ['Q1' => '25%', 'Q1_Target' => '25%', 'Q1_Cum_Target' => '25%', 'Q1_Cum_Prog' => '25%', 'Q1_Quarterly_Cum' => '25%', 'Q1_Overall_Prog_Final' => '100%'], 'actual_exp' => ['Q1' => '2.42'], 'timeline_status' => 'Completed'],
                    ['serial_no' => '8', 'project_cord' => 'DGCA& CEO', 'institution' => 'CAASL', 'category' => 'New', 'division' => 'Direction & Management', 'project_name' => 'STRENGTHING AND REGULARIZING THE ACTIVITIES OF INFORMATION AND COMMUNICATION TECHNOLOGY', 'location' => 'CAASL', 'allocation_2026_original' => '38.99', 'allocation_2026_revised' => '38.99', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '9.75', 'phys_percent' => ['Q1' => '25%', 'Q1_Target' => '25%', 'Q1_Cum_Target' => '25%', 'Q1_Cum_Prog' => '25%', 'Q1_Quarterly_Cum' => '25%', 'Q1_Overall_Prog_Final' => '100%'], 'actual_exp' => ['Q1' => '8.8'], 'timeline_status' => 'Completed'],
                    ['serial_no' => '9', 'project_cord' => 'DGCA& CEO', 'institution' => 'CAASL', 'category' => 'New', 'division' => 'Direction & Management', 'project_name' => 'STRENGTHING AND REGULARIZING THE ACTIVITIES OF TECHNICAL LIBRARY & USOAP CMA PROGRAM (TL)', 'location' => 'CAASL', 'allocation_2026_original' => '11.69', 'allocation_2026_revised' => '11.69', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '2.92', 'phys_percent' => ['Q1' => '25%', 'Q1_Target' => '25%', 'Q1_Cum_Target' => '25%', 'Q1_Cum_Prog' => '25%', 'Q1_Quarterly_Cum' => '25%', 'Q1_Overall_Prog_Final' => '100%'], 'actual_exp' => ['Q1' => '2.63'], 'timeline_status' => 'Completed'],
                    ['serial_no' => '10', 'project_cord' => 'DDG - ASR', 'institution' => 'CAASL', 'category' => 'New', 'division' => 'Aeronautical Service Regulations', 'project_name' => 'STRENGTHING AND REGULARIZING THE ACTIVITIES OF AIR NAVIGATION SERVICES', 'location' => 'CAASL', 'allocation_2026_original' => '70.07', 'allocation_2026_revised' => '70.07', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '17.52', 'phys_percent' => ['Q1' => '25%', 'Q1_Target' => '25%', 'Q1_Cum_Target' => '25%', 'Q1_Cum_Prog' => '25%', 'Q1_Quarterly_Cum' => '25%', 'Q1_Overall_Prog_Final' => '100%'], 'actual_exp' => ['Q1' => '10.11'], 'timeline_status' => 'Completed'],
                    ['serial_no' => '11', 'project_cord' => 'DDG - ASR', 'institution' => 'CAASL', 'category' => 'New', 'division' => 'Aeronautical Service Regulations', 'project_name' => 'STRENGTHING AND REGULARIZING THE ACTIVITIES OF AERODROMES SECTION', 'location' => 'CAASL', 'allocation_2026_original' => '49.5', 'allocation_2026_revised' => '49.5', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '12.38', 'phys_percent' => ['Q1' => '25%', 'Q1_Target' => '25%', 'Q1_Cum_Target' => '25%', 'Q1_Cum_Prog' => '25%', 'Q1_Quarterly_Cum' => '25%', 'Q1_Overall_Prog_Final' => '100%'], 'actual_exp' => ['Q1' => '8.74'], 'timeline_status' => 'Completed'],
                    ['serial_no' => '12', 'project_cord' => 'DDG - AT&SR', 'institution' => 'CAASL', 'category' => 'New', 'division' => 'Air Transport & Security Regulations', 'project_name' => 'STRENGTHING AND REGULARIZING THE ACTIVITIES OF AVIATION SECURITY', 'location' => 'CAASL', 'allocation_2026_original' => '49.98', 'allocation_2026_revised' => '49.98', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '12.50', 'phys_percent' => ['Q1' => '25%', 'Q1_Target' => '25%', 'Q1_Cum_Target' => '25%', 'Q1_Cum_Prog' => '25%', 'Q1_Quarterly_Cum' => '25%', 'Q1_Overall_Prog_Final' => '100%'], 'actual_exp' => ['Q1' => '8.54'], 'timeline_status' => 'Completed'],
                    ['serial_no' => '13', 'project_cord' => 'DDG - FSR', 'institution' => 'CAASL', 'category' => 'New', 'division' => 'Flight Safety Regulations', 'project_name' => 'AIRCRAFT REGISTRATION AND AIRWORTHINESS', 'location' => 'CAASL', 'allocation_2026_original' => '77.54', 'allocation_2026_revised' => '77.54', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '19.39', 'phys_percent' => ['Q1' => '25%', 'Q1_Target' => '25%', 'Q1_Cum_Target' => '25%', 'Q1_Cum_Prog' => '25%', 'Q1_Quarterly_Cum' => '25%', 'Q1_Overall_Prog_Final' => '100%'], 'actual_exp' => ['Q1' => '12.32'], 'timeline_status' => 'Completed'],
                    ['serial_no' => '14', 'project_cord' => 'DDG - FSR', 'institution' => 'CAASL', 'category' => 'New', 'division' => 'Flight Safety Regulations', 'project_name' => 'STRENGTHING AND REGULARIZING THE ACTIVITIES OF TRAINING ORGANIZATION AND PERSONNEL LICENSING', 'location' => 'CAASL', 'allocation_2026_original' => '92.6', 'allocation_2026_revised' => '92.6', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '23.15', 'phys_percent' => ['Q1' => '25%', 'Q1_Target' => '25%', 'Q1_Cum_Target' => '25%', 'Q1_Cum_Prog' => '25%', 'Q1_Quarterly_Cum' => '25%', 'Q1_Overall_Prog_Final' => '100%'], 'actual_exp' => ['Q1' => '12.64'], 'timeline_status' => 'Completed'],
                    ['serial_no' => '15', 'project_cord' => 'DDG - FSR', 'institution' => 'CAASL', 'category' => 'New', 'division' => 'Flight Safety Regulations', 'project_name' => 'STRENGTHING AND REGULARIZING THE ACTIVITIES OF AIRCRAFT OPERATIONS SECTION', 'location' => 'CAASL', 'allocation_2026_original' => '97.55', 'allocation_2026_revised' => '97.55', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '24.39', 'phys_percent' => ['Q1' => '25%', 'Q1_Target' => '25%', 'Q1_Cum_Target' => '25%', 'Q1_Cum_Prog' => '25%', 'Q1_Quarterly_Cum' => '25%', 'Q1_Overall_Prog_Final' => '100%'], 'actual_exp' => ['Q1' => '14.86'], 'timeline_status' => 'Completed'],
                    ['serial_no' => '16', 'project_cord' => 'DDG - AT&SR', 'institution' => 'CAASL', 'category' => 'New', 'division' => 'Air Transport & Security Regulations', 'project_name' => 'STRENGTHING AND REGULARIZING THE ACTIVITIES OF AIR TRANSPORT & ECONOMIC REGULATION', 'location' => 'CAASL', 'allocation_2026_original' => '30.16', 'allocation_2026_revised' => '30.16', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '7.54', 'phys_percent' => ['Q1' => '25%', 'Q1_Target' => '25%', 'Q1_Cum_Target' => '25%', 'Q1_Cum_Prog' => '25%', 'Q1_Quarterly_Cum' => '25%', 'Q1_Overall_Prog_Final' => '100%'], 'actual_exp' => ['Q1' => '6.2'], 'timeline_status' => 'Completed'],
                    ['serial_no' => '17', 'project_cord' => 'DDG-CM', 'institution' => 'CAASL', 'category' => 'New', 'division' => 'Corporate Management', 'project_name' => 'HUMAN RESOURCES AND PROPERTY MANAGEMENT', 'location' => 'CAASL', 'allocation_2026_original' => '123.64', 'allocation_2026_revised' => '123.64', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '30.91', 'phys_percent' => ['Q1' => '25%', 'Q1_Target' => '25%', 'Q1_Cum_Target' => '25%', 'Q1_Cum_Prog' => '25%', 'Q1_Quarterly_Cum' => '25%', 'Q1_Overall_Prog_Final' => '100%'], 'actual_exp' => ['Q1' => '12.61'], 'timeline_status' => 'Completed'],
                    ['serial_no' => '18', 'project_cord' => 'DDG-CM', 'institution' => 'CAASL', 'category' => 'New', 'division' => 'Corporate Management', 'project_name' => 'FINANCE AND REVENUE MANAGEMENT', 'location' => 'CAASL', 'allocation_2026_original' => '126.08', 'allocation_2026_revised' => '126.08', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '31.52', 'phys_percent' => ['Q1' => '25%', 'Q1_Target' => '25%', 'Q1_Cum_Target' => '25%', 'Q1_Cum_Prog' => '25%', 'Q1_Quarterly_Cum' => '25%', 'Q1_Overall_Prog_Final' => '100%'], 'actual_exp' => ['Q1' => '25.83'], 'timeline_status' => 'Completed'],
                    ['serial_no' => '19', 'project_cord' => 'DGCA& CEO', 'institution' => 'CAASL', 'category' => 'New', 'division' => 'Direction & Management', 'project_name' => 'ACTIVITIES OF AVIATION PROMOTION', 'location' => 'CAASL', 'allocation_2026_original' => '15.87', 'allocation_2026_revised' => '15.87', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '3.97', 'phys_percent' => ['Q1' => '25%', 'Q1_Target' => '25%', 'Q1_Cum_Target' => '25%', 'Q1_Cum_Prog' => '25%', 'Q1_Quarterly_Cum' => '25%', 'Q1_Overall_Prog_Final' => '100%'], 'actual_exp' => ['Q1' => '3.42'], 'timeline_status' => 'Completed'],
                    ['serial_no' => '20', 'project_cord' => 'DGCA & CM', 'institution' => 'CAASL', 'category' => 'New', 'division' => 'Corporate Management', 'project_name' => 'ACTIVITIES OF COMMON', 'location' => 'CAASL', 'allocation_2026_original' => '419.51', 'allocation_2026_revised' => '419.51', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '104.88', 'phys_percent' => ['Q1' => '25%', 'Q1_Target' => '25%', 'Q1_Cum_Target' => '25%', 'Q1_Cum_Prog' => '25%', 'Q1_Quarterly_Cum' => '25%', 'Q1_Overall_Prog_Final' => '100%'], 'actual_exp' => ['Q1' => '63.59'], 'timeline_status' => 'Completed'],
                ]
            ]
        ],
        'ports' => [
            'SLPA' => [
                'institution_name' => 'Sri Lanka Ports Authority',
                'projects' => [
                    // --- 1. DEVELOPMENT (10 Projects) ---
                    ['serial_no' => '12', 'institution' => 'SLPA', 'category' => 'Continuous', 'division' => 'Development', 'project_name' => 'Rehabilitation of KKS harbour - Consultancy', 'location' => 'KKS', 'allocation_2026_original' => '300', 'allocation_2026_revised' => '0', 'cum_exp_2025' => '197.5', 'cum_phys_2025' => '47%', 'q1_fin_target' => '197.5', 'phys_percent' => ['Q1' => '0%', 'Q1_Target' => '0%', 'Q1_Cum_Target' => '0.01%', 'Q1_Cum_Prog' => '0%', 'Q1_Overall_Prog_Final' => '0%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'Delayed'],
                    ['serial_no' => '13', 'institution' => 'SLPA', 'category' => 'Continuous', 'division' => 'Development', 'project_name' => 'Rehabilitation of KKS harbour - Construction', 'location' => 'KKS', 'allocation_2026_original' => '0', 'allocation_2026_revised' => '0', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '0%', 'Q1_Target' => '0%', 'Q1_Cum_Target' => '0%', 'Q1_Cum_Prog' => '0%', 'Q1_Overall_Prog_Final' => '0%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'Delayed'],
                    ['serial_no' => '14', 'institution' => 'SLPA', 'category' => 'Continuous', 'division' => 'Development', 'project_name' => 'Boundary wall and fence for balance land', 'location' => 'KKS', 'allocation_2026_original' => '20', 'allocation_2026_revised' => '0', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '12%', 'Q1_Target' => '15%', 'Q1_Cum_Target' => '0%', 'Q1_Cum_Prog' => '12%', 'Q1_Overall_Prog_Final' => '0%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '15', 'institution' => 'SLPA', 'category' => 'Continuous', 'division' => 'Development', 'project_name' => 'Security rest room at gate', 'location' => 'KKS', 'allocation_2026_original' => '20', 'allocation_2026_revised' => '0', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '15%', 'Q1_Target' => '15%', 'Q1_Cum_Target' => '0%', 'Q1_Cum_Prog' => '15%', 'Q1_Overall_Prog_Final' => '0%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '16', 'institution' => 'SLPA', 'category' => 'Continuous', 'division' => 'Development', 'project_name' => 'Modification of Passenger Terminal Building KKS', 'location' => 'KKS', 'allocation_2026_original' => '15', 'allocation_2026_revised' => '0', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '10%', 'Q1_Target' => '15%', 'Q1_Cum_Target' => '0%', 'Q1_Cum_Prog' => '10%', 'Q1_Overall_Prog_Final' => '0%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '17', 'institution' => 'SLPA', 'category' => 'Continuous', 'division' => 'Development', 'project_name' => 'Facilities SLPA workshop complex', 'location' => 'Colombo', 'allocation_2026_original' => '60', 'allocation_2026_revised' => '81.74', 'cum_exp_2025' => '38', 'cum_phys_2025' => '50%', 'q1_fin_target' => '50', 'phys_percent' => ['Q1' => '3%', 'Q1_Target' => '5%', 'Q1_Cum_Target' => '0%', 'Q1_Cum_Prog' => '3%', 'Q1_Overall_Prog_Final' => '0%'], 'actual_exp' => ['Q1' => '8.7'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '18', 'institution' => 'SLPA', 'category' => 'Continuous', 'division' => 'Development', 'project_name' => 'Workshop Building Complex (Final)', 'location' => 'Colombo', 'allocation_2026_original' => '275', 'allocation_2026_revised' => '0', 'cum_exp_2025' => '1731', 'cum_phys_2025' => '100%', 'q1_fin_target' => '550', 'phys_percent' => ['Q1' => '0%', 'Q1_Target' => '0%', 'Q1_Cum_Target' => '0%', 'Q1_Cum_Prog' => '0%', 'Q1_Overall_Prog_Final' => '0%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'Completed'],
                    ['serial_no' => '19', 'institution' => 'SLPA', 'category' => 'Continuous', 'division' => 'Development', 'project_name' => 'Furniture & interior SLPA MFC', 'location' => 'Colombo', 'allocation_2026_original' => '1000', 'allocation_2026_revised' => '0', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '0%', 'Q1_Target' => '0%', 'Q1_Cum_Target' => '0%', 'Q1_Cum_Prog' => '0%', 'Q1_Overall_Prog_Final' => '0%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '20', 'institution' => 'SLPA', 'category' => 'Continuous', 'division' => 'Development', 'project_name' => 'Chairman Office renovation balance', 'location' => 'Colombo', 'allocation_2026_original' => '45.66', 'allocation_2026_revised' => '0', 'cum_exp_2025' => '13', 'cum_phys_2025' => '0%', 'q1_fin_target' => '60', 'phys_percent' => ['Q1' => '40%', 'Q1_Target' => '45%', 'Q1_Cum_Target' => '0%', 'Q1_Cum_Prog' => '40%', 'Q1_Overall_Prog_Final' => '16%'], 'actual_exp' => ['Q1' => '16'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '21', 'institution' => 'SLPA', 'category' => 'Continuous', 'division' => 'Development', 'project_name' => 'Detail Design western breakwater CPEP II', 'location' => 'Colombo', 'allocation_2026_original' => '900', 'allocation_2026_revised' => '0', 'cum_exp_2025' => '91', 'cum_phys_2025' => '15%', 'q1_fin_target' => '270', 'phys_percent' => ['Q1' => '5%', 'Q1_Target' => '10%', 'Q1_Cum_Target' => '0%', 'Q1_Cum_Prog' => '5%', 'Q1_Overall_Prog_Final' => '5%'], 'actual_exp' => ['Q1' => '76.65'], 'timeline_status' => 'On Track'],

                    // --- 2. PLANNING & DEVELOPMENT (3 Projects) ---
                    ['serial_no' => '7-PD', 'institution' => 'SLPA', 'category' => 'New', 'division' => 'Planning & Development', 'project_name' => 'Relocation of Port Access Gate', 'location' => 'Colombo', 'allocation_2026_original' => '60', 'allocation_2026_revised' => '0', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '7%', 'Q1_Target' => '7%', 'Q1_Cum_Target' => '7%', 'Q1_Cum_Prog' => '7%', 'Q1_Overall_Prog_Final' => '1%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '8-PD', 'institution' => 'SLPA', 'category' => 'New', 'division' => 'Planning & Development', 'project_name' => 'Revision National Port Master Plan', 'location' => 'Colombo', 'allocation_2026_original' => '300', 'allocation_2026_revised' => '125', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '8%', 'Q1_Target' => '8%', 'Q1_Cum_Target' => '8%', 'Q1_Cum_Prog' => '8%', 'Q1_Overall_Prog_Final' => '1%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '9-PD', 'institution' => 'SLPA', 'category' => 'New', 'division' => 'Planning & Development', 'project_name' => 'Studies North Port Development', 'location' => 'Colombo', 'allocation_2026_original' => '300', 'allocation_2026_revised' => '96', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '7%', 'Q1_Target' => '7%', 'Q1_Cum_Target' => '7%', 'Q1_Cum_Prog' => '7%', 'Q1_Overall_Prog_Final' => '1%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track'],

                    // --- 3. ELECTRICAL & ELECTRONIC (4 Projects) ---
                    ['serial_no' => '33-EE', 'institution' => 'SLPA', 'category' => 'Continuous', 'division' => 'Electrical & Electronic', 'project_name' => 'Solar System ECT Operation Building', 'location' => 'ECT', 'allocation_2026_original' => '49', 'allocation_2026_revised' => '0', 'cum_exp_2025' => '0', 'cum_phys_2025' => '25%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '5%', 'Q1_Target' => '5%', 'Q1_Cum_Target' => '30%', 'Q1_Cum_Prog' => '5%', 'Q1_Overall_Prog_Final' => '0.16%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '34-EE', 'institution' => 'SLPA', 'category' => 'Continuous', 'division' => 'Electrical & Electronic', 'project_name' => 'Shore Power Supply System ECT', 'location' => 'ECT', 'allocation_2026_original' => '299', 'allocation_2026_revised' => '0', 'cum_exp_2025' => '0', 'cum_phys_2025' => '8%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '2%', 'Q1_Target' => '2%', 'Q1_Cum_Target' => '10%', 'Q1_Cum_Prog' => '2%', 'Q1_Overall_Prog_Final' => '0.20%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '1-EE-NEW', 'institution' => 'SLPA', 'category' => 'New', 'division' => 'Electrical & Electronic', 'project_name' => 'Electrification 02 Nos. ECT RTG', 'location' => 'ECT', 'allocation_2026_original' => '449', 'allocation_2026_revised' => '0', 'cum_exp_2025' => '0', 'cum_phys_2025' => '5%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '10%', 'Q1_Target' => '10%', 'Q1_Cum_Target' => '10%', 'Q1_Cum_Prog' => '10%', 'Q1_Overall_Prog_Final' => '1%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '2-EE-NEW', 'institution' => 'SLPA', 'category' => 'New', 'division' => 'Electrical & Electronic', 'project_name' => 'Rooftop Solar PG W/H', 'location' => 'Peliyagoda', 'allocation_2026_original' => '90', 'allocation_2026_revised' => '0', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '0%', 'Q1_Target' => '5%', 'Q1_Cum_Target' => '5%', 'Q1_Cum_Prog' => '0%', 'Q1_Overall_Prog_Final' => '0%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'At Risk'],

                    // --- 4. NAVIGATION (2 Projects) ---
                    ['serial_no' => '1-NAV', 'institution' => 'SLPA', 'category' => 'New', 'division' => 'Navigation', 'project_name' => 'Vessel Traffic Management Port Control', 'location' => 'Colombo', 'allocation_2026_original' => '600', 'allocation_2026_revised' => '600', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '0%', 'Q1_Target' => '0%', 'Q1_Cum_Target' => '0.25%', 'Q1_Cum_Prog' => '0%', 'Q1_Overall_Prog_Final' => '0%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'Postponed'],
                    ['serial_no' => '2-NAV', 'institution' => 'SLPA', 'category' => 'New', 'division' => 'Navigation', 'project_name' => 'Renovation Kovilan light house', 'location' => 'Jaffna', 'allocation_2026_original' => '100', 'allocation_2026_revised' => '100', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '20%', 'Q1_Target' => '20%', 'Q1_Cum_Target' => '0.15%', 'Q1_Cum_Prog' => '20%', 'Q1_Overall_Prog_Final' => '15%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track'],

                    // --- 5. CIVIL ENGINEERING (5 Projects) ---
                    ['serial_no' => '38-CE', 'institution' => 'SLPA', 'category' => 'Continuous', 'division' => 'Civil Engineering', 'project_name' => 'Proposed Stores Building Civil Eng.', 'location' => 'Colombo', 'allocation_2026_original' => '25', 'allocation_2026_revised' => '0', 'cum_exp_2025' => '65.15', 'cum_phys_2025' => '72%', 'q1_fin_target' => '420', 'phys_percent' => ['Q1' => '75%', 'Q1_Target' => '80%', 'Q1_Cum_Target' => '80%', 'Q1_Cum_Prog' => '75%', 'Q1_Overall_Prog_Final' => '94%'], 'actual_exp' => ['Q1' => '65.15'], 'timeline_status' => 'Delayed'],
                    ['serial_no' => '39-CE', 'institution' => 'SLPA', 'category' => 'Continuous', 'division' => 'Civil Engineering', 'project_name' => 'Fork Lift Repair Section (Balance)', 'location' => 'Colombo', 'allocation_2026_original' => '25', 'allocation_2026_revised' => '0', 'cum_exp_2025' => '73.52', 'cum_phys_2025' => '65%', 'q1_fin_target' => '10', 'phys_percent' => ['Q1' => '80%', 'Q1_Target' => '70%', 'Q1_Cum_Target' => '70%', 'Q1_Cum_Prog' => '80%', 'Q1_Overall_Prog_Final' => '100%'], 'actual_exp' => ['Q1' => '73.52'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '40-CE', 'institution' => 'SLPA', 'category' => 'Continuous', 'division' => 'Civil Engineering', 'project_name' => 'Rectification Reefer Container Yard', 'location' => 'Colombo', 'allocation_2026_original' => '75', 'allocation_2026_revised' => '0', 'cum_exp_2025' => '12.3', 'cum_phys_2025' => '0%', 'q1_fin_target' => '12.5', 'phys_percent' => ['Q1' => '20%', 'Q1_Target' => '20%', 'Q1_Cum_Target' => '20%', 'Q1_Cum_Prog' => '20%', 'Q1_Overall_Prog_Final' => '100%'], 'actual_exp' => ['Q1' => '12.3'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '41-CE', 'institution' => 'SLPA', 'category' => 'Continuous', 'division' => 'Civil Engineering', 'project_name' => 'Rectification Dangerous Cargo Yard', 'location' => 'Colombo', 'allocation_2026_original' => '75', 'allocation_2026_revised' => '0', 'cum_exp_2025' => '14', 'cum_phys_2025' => '0%', 'q1_fin_target' => '14.5', 'phys_percent' => ['Q1' => '20%', 'Q1_Target' => '20%', 'Q1_Cum_Target' => '20%', 'Q1_Cum_Prog' => '20%', 'Q1_Overall_Prog_Final' => '100%'], 'actual_exp' => ['Q1' => '14'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '15-CE-NEW', 'institution' => 'SLPA', 'category' => 'New', 'division' => 'Civil Engineering', 'project_name' => 'Renovation Container Yard Peliyagoda', 'location' => 'Peliyagoda', 'allocation_2026_original' => '50', 'allocation_2026_revised' => '0', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '0%', 'Q1_Target' => '0%', 'Q1_Cum_Target' => '0%', 'Q1_Cum_Prog' => '0%', 'Q1_Overall_Prog_Final' => '0%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track'],

                    // --- 6. LOGISTICS (1 Project) ---
                    ['serial_no' => '18-LOG', 'institution' => 'SLPA', 'category' => 'New', 'division' => 'Logistics', 'project_name' => 'Fire detention system SLPA warehouse', 'location' => 'Logistics', 'allocation_2026_original' => '70', 'allocation_2026_revised' => '0', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '10', 'phys_percent' => ['Q1' => '10%', 'Q1_Target' => '0%', 'Q1_Cum_Target' => '0.2%', 'Q1_Cum_Prog' => '10%', 'Q1_Overall_Prog_Final' => '0.5%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track'],

                    // --- 7. C & D (15 Projects) ---
                    ['serial_no' => '1-CD', 'institution' => 'SLPA', 'category' => 'Continuation', 'division' => 'C & D', 'project_name' => 'Operation Building ECT - Civil', 'location' => 'Colombo', 'allocation_2026_original' => '720', 'allocation_2026_revised' => '431.65', 'cum_exp_2025' => '100%', 'cum_phys_2025' => '100%', 'q1_fin_target' => '498.9', 'phys_percent' => ['Q1' => '0%', 'Q1_Target' => '0%', 'Q1_Cum_Target' => '100%', 'Q1_Cum_Prog' => '100%', 'Q1_Overall_Prog_Final' => '100%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'Completed'],
                    ['serial_no' => '2-CD', 'institution' => 'SLPA', 'category' => 'Continuation', 'division' => 'C & D', 'project_name' => 'Operation Building ECT - Misc', 'location' => 'Colombo', 'allocation_2026_original' => '60', 'allocation_2026_revised' => '205.91', 'cum_exp_2025' => '100%', 'cum_phys_2025' => '100%', 'q1_fin_target' => '233', 'phys_percent' => ['Q1' => '100%', 'Q1_Target' => '100%', 'Q1_Cum_Target' => '100%', 'Q1_Cum_Prog' => '100%', 'Q1_Overall_Prog_Final' => '100%'], 'actual_exp' => ['Q1' => '55.06'], 'timeline_status' => 'Completed'],
                    ['serial_no' => '3-CD', 'institution' => 'SLPA', 'category' => 'Continuation', 'division' => 'C & D', 'project_name' => 'Water Supplying System ECT Building', 'location' => 'Colombo', 'allocation_2026_original' => '0.15', 'allocation_2026_revised' => '4.17', 'cum_exp_2025' => '100%', 'cum_phys_2025' => '100%', 'q1_fin_target' => '5.07', 'phys_percent' => ['Q1' => '0%', 'Q1_Target' => '0%', 'Q1_Cum_Target' => '100%', 'Q1_Cum_Prog' => '100%', 'Q1_Overall_Prog_Final' => '100%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'Completed'],
                    ['serial_no' => '4-CD', 'institution' => 'SLPA', 'category' => 'Continuation', 'division' => 'C & D', 'project_name' => 'STP & Landscaping ECT Building', 'location' => 'Colombo', 'allocation_2026_original' => '75', 'allocation_2026_revised' => '0', 'cum_exp_2025' => '0%', 'cum_phys_2025' => '0%', 'q1_fin_target' => '750', 'phys_percent' => ['Q1' => '50%', 'Q1_Target' => '50%', 'Q1_Cum_Target' => '10%', 'Q1_Cum_Prog' => '75%', 'Q1_Overall_Prog_Final' => '5%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '5-CD', 'institution' => 'SLPA', 'category' => 'Continuation', 'division' => 'C & D', 'project_name' => 'Electrical works of ECT Building', 'location' => 'Colombo', 'allocation_2026_original' => '470', 'allocation_2026_revised' => '426', 'cum_exp_2025' => '98%', 'cum_phys_2025' => '98%', 'q1_fin_target' => '82.26', 'phys_percent' => ['Q1' => '100%', 'Q1_Target' => '100%', 'Q1_Cum_Target' => '100%', 'Q1_Cum_Prog' => '100%', 'Q1_Overall_Prog_Final' => '100%'], 'actual_exp' => ['Q1' => '742.26'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '6-CD', 'institution' => 'SLPA', 'category' => 'Continuation', 'division' => 'C & D', 'project_name' => 'Port Access Road Trincomalee', 'location' => 'Trincomalee', 'allocation_2026_original' => '260', 'allocation_2026_revised' => '0', 'cum_exp_2025' => '100%', 'cum_phys_2025' => '100%', 'q1_fin_target' => '400', 'phys_percent' => ['Q1' => '100%', 'Q1_Target' => '100%', 'Q1_Cum_Target' => '10%', 'Q1_Cum_Prog' => '100%', 'Q1_Overall_Prog_Final' => '5%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '7-CD', 'institution' => 'SLPA', 'category' => 'Continuation', 'division' => 'C & D', 'project_name' => 'Rehabilitaion Seram Gate Road', 'location' => 'Colombo', 'allocation_2026_original' => '125', 'allocation_2026_revised' => '0', 'cum_exp_2025' => '100%', 'cum_phys_2025' => '100%', 'q1_fin_target' => '180', 'phys_percent' => ['Q1' => '100%', 'Q1_Target' => '100%', 'Q1_Cum_Target' => '10%', 'Q1_Cum_Prog' => '100%', 'Q1_Overall_Prog_Final' => '5%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '8-CD', 'institution' => 'SLPA', 'category' => 'Continuation', 'division' => 'C & D', 'project_name' => 'Paving works at JCT-V', 'location' => 'Colombo', 'allocation_2026_original' => '500', 'allocation_2026_revised' => '194.27', 'cum_exp_2025' => '17%', 'cum_phys_2025' => '17%', 'q1_fin_target' => '200', 'phys_percent' => ['Q1' => '44%', 'Q1_Target' => '48%', 'Q1_Cum_Target' => '60%', 'Q1_Cum_Prog' => '29%', 'Q1_Overall_Prog_Final' => '46%'], 'actual_exp' => ['Q1' => '58.87'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '9-CD', 'institution' => 'SLPA', 'category' => 'Continuation', 'division' => 'C & D', 'project_name' => 'Civil works JCT V Development', 'location' => 'Colombo', 'allocation_2026_original' => '128.6', 'allocation_2026_revised' => '39.97', 'cum_exp_2025' => '100%', 'cum_phys_2025' => '100%', 'q1_fin_target' => '8406', 'phys_percent' => ['Q1' => '0%', 'Q1_Target' => '0%', 'Q1_Cum_Target' => '100%', 'Q1_Cum_Prog' => '100%', 'Q1_Overall_Prog_Final' => '100%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'Completed'],
                    ['serial_no' => '10-CD', 'institution' => 'SLPA', 'category' => 'Continuation', 'division' => 'C & D', 'project_name' => 'Yard Rehabilitsion PVQ Colombo', 'location' => 'Colombo', 'allocation_2026_original' => '6.78', 'allocation_2026_revised' => '164.9', 'cum_exp_2025' => '100%', 'cum_phys_2025' => '100%', 'q1_fin_target' => '229', 'phys_percent' => ['Q1' => '0%', 'Q1_Target' => '0%', 'Q1_Cum_Target' => '100%', 'Q1_Cum_Prog' => '100%', 'Q1_Overall_Prog_Final' => '100%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'Completed'],
                    ['serial_no' => '11-CD', 'institution' => 'SLPA', 'category' => 'Continuation', 'division' => 'C & D', 'project_name' => 'ECT Civil Works - Phase II', 'location' => 'Colombo', 'allocation_2026_original' => '25328', 'allocation_2026_revised' => '49218', 'cum_exp_2025' => '71.95%', 'cum_phys_2025' => '71.95%', 'q1_fin_target' => '8403', 'phys_percent' => ['Q1' => '6.75%', 'Q1_Target' => '9.4%', 'Q1_Cum_Target' => '81.3%', 'Q1_Cum_Prog' => '1.8%', 'Q1_Overall_Prog_Final' => '6.7%'], 'actual_exp' => ['Q1' => '661.2'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '12-CD-NEW', 'institution' => 'SLPA', 'category' => 'New', 'division' => 'C & D', 'project_name' => 'ECT Work Shop Building', 'location' => 'Colombo', 'allocation_2026_original' => '360', 'allocation_2026_revised' => '0', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '1800', 'phys_percent' => ['Q1' => '0%', 'Q1_Target' => '0%', 'Q1_Cum_Target' => '0%', 'Q1_Cum_Prog' => '0%', 'Q1_Overall_Prog_Final' => '0%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'Delayed'],
                    ['serial_no' => '13-CD-NEW', 'institution' => 'SLPA', 'category' => 'New', 'division' => 'C & D', 'project_name' => 'Port Internal Road Network', 'location' => 'Colombo', 'allocation_2026_original' => '195', 'allocation_2026_revised' => '0', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '195', 'phys_percent' => ['Q1' => '5%', 'Q1_Target' => '80%', 'Q1_Cum_Target' => '54%', 'Q1_Cum_Prog' => '4%', 'Q1_Overall_Prog_Final' => '4%'], 'actual_exp' => ['Q1' => '10'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '14-CD-NEW', 'institution' => 'SLPA', 'category' => 'New', 'division' => 'C & D', 'project_name' => 'ILB Yard Custom Scanning Facility', 'location' => 'Colombo', 'allocation_2026_original' => '100', 'allocation_2026_revised' => '0', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '153', 'phys_percent' => ['Q1' => '100%', 'Q1_Target' => '100%', 'Q1_Cum_Target' => '10%', 'Q1_Cum_Prog' => '10%', 'Q1_Overall_Prog_Final' => '10%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '15-CD-NEW', 'institutionC&D,IS,Mechenical,security,CE(Poroject),these all divionsa are not in database add those ' => 'SLPA', 'category' => 'New', 'division' => 'C & D', 'project_name' => 'Development of New Kitchen', 'location' => 'Colombo', 'allocation_2026_original' => '340', 'allocation_2026_revised' => '0', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '650', 'phys_percent' => ['Q1' => '100%', 'Q1_Target' => '50%', 'Q1_Cum_Target' => '15%', 'Q1_Cum_Prog' => '10%', 'Q1_Overall_Prog_Final' => '10%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'Delayed'],

                    // --- 8. MECHANICAL (15 Projects) ---
                    ['serial_no' => '22-MECH', 'institution' => 'SLPA', 'category' => 'Continuation', 'division' => 'Mechanical', 'project_name' => 'Procurement of STS cranes & ARMGs', 'location' => 'ECT', 'allocation_2026_original' => '64000', 'allocation_2026_revised' => '102313', 'cum_exp_2025' => '94244', 'cum_phys_2025' => '98%', 'q1_fin_target' => '9915', 'phys_percent' => ['Q1' => '98%', 'Q1_Target' => '98%', 'Q1_Cum_Target' => '0.01%', 'Q1_Cum_Prog' => '98%', 'Q1_Overall_Prog_Final' => '98%'], 'actual_exp' => ['Q1' => '9041'], 'timeline_status' => 'Delayed'],
                    ['serial_no' => '23-MECH', 'institution' => 'SLPA', 'category' => 'Continuation', 'division' => 'Mechanical', 'project_name' => 'Terminal Tractor JCT', 'location' => 'JCT', 'allocation_2026_original' => '999', 'allocation_2026_revised' => '0', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '10000', 'phys_percent' => ['Q1' => '10%', 'Q1_Target' => '10%', 'Q1_Cum_Target' => '10%', 'Q1_Cum_Prog' => '10%', 'Q1_Overall_Prog_Final' => '10%'], 'actual_exp' => ['Q1' => '200'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '24-MECH', 'institution' => 'SLPA', 'category' => 'Continuation', 'division' => 'Mechanical', 'project_name' => 'Transfer Crane JCT', 'location' => 'JCT', 'allocation_2026_original' => '8875', 'allocation_2026_revised' => '0', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '90000', 'phys_percent' => ['Q1' => '10%', 'Q1_Target' => '10%', 'Q1_Cum_Target' => '10%', 'Q1_Cum_Prog' => '10%', 'Q1_Overall_Prog_Final' => '10%'], 'actual_exp' => ['Q1' => '100'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '25-MECH', 'institution' => 'SLPA', 'category' => 'Continuation', 'division' => 'Mechanical', 'project_name' => 'Straddle Carriers (Hybrid) ECT', 'location' => 'ECT', 'allocation_2026_original' => '9749', 'allocation_2026_revised' => '0', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '16796', 'phys_percent' => ['Q1' => '15%', 'Q1_Target' => '15%', 'Q1_Cum_Target' => '15%', 'Q1_Cum_Prog' => '15%', 'Q1_Overall_Prog_Final' => '15%'], 'actual_exp' => ['Q1' => '150'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '26-MECH', 'institution' => 'SLPA', 'category' => 'New', 'division' => 'Mechanical', 'project_name' => 'Platforms for Unloading ECT', 'location' => 'ECT', 'allocation_2026_original' => '10000', 'allocation_2026_revised' => '0', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '1000', 'phys_percent' => ['Q1' => '5%', 'Q1_Target' => '5%', 'Q1_Cum_Target' => '5%', 'Q1_Cum_Prog' => '5%', 'Q1_Overall_Prog_Final' => '5%'], 'actual_exp' => ['Q1' => '50'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '27-MECH', 'institution' => 'SLPA', 'category' => 'Continuation', 'division' => 'Mechanical', 'project_name' => 'Fork Lift Truck (30Ton) ECT', 'location' => 'ECT', 'allocation_2026_original' => '149', 'allocation_2026_revised' => '0', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '1500', 'phys_percent' => ['Q1' => '10%', 'Q1_Target' => '10%', 'Q1_Cum_Target' => '10%', 'Q1_Cum_Prog' => '10%', 'Q1_Overall_Prog_Final' => '10%'], 'actual_exp' => ['Q1' => '300'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '28-MECH', 'institution' => 'SLPA', 'category' => 'Continuation', 'division' => 'Mechanical', 'project_name' => 'Reach Stackers JCT', 'location' => 'JCT', 'allocation_2026_original' => '359', 'allocation_2026_revised' => '0', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '3600', 'phys_percent' => ['Q1' => '10%', 'Q1_Target' => '10%', 'Q1_Cum_Target' => '10%', 'Q1_Cum_Prog' => '10%', 'Q1_Overall_Prog_Final' => '10%'], 'actual_exp' => ['Q1' => '300'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '29-MECH', 'institution' => 'SLPA', 'category' => 'Continuation', 'division' => 'Mechanical', 'project_name' => 'Reach Stackers ECT', 'location' => 'ECT', 'allocation_2026_original' => '199', 'allocation_2026_revised' => '0', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '2000', 'phys_percent' => ['Q1' => '10%', 'Q1_Target' => '10%', 'Q1_Cum_Target' => '10%', 'Q1_Cum_Prog' => '10%', 'Q1_Overall_Prog_Final' => '10%'], 'actual_exp' => ['Q1' => '300'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '30-MECH', 'institution' => 'SLPA', 'category' => 'Continuation', 'division' => 'Mechanical', 'project_name' => '160 Ton Mobile Crane ECT', 'location' => 'ECT', 'allocation_2026_original' => '349', 'allocation_2026_revised' => '0', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '3500', 'phys_percent' => ['Q1' => '10%', 'Q1_Target' => '10%', 'Q1_Cum_Target' => '10%', 'Q1_Cum_Prog' => '10%', 'Q1_Overall_Prog_Final' => '10%'], 'actual_exp' => ['Q1' => '300'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '31-MECH', 'institution' => 'SLPA', 'category' => 'Continuation', 'division' => 'Mechanical', 'project_name' => 'Prime Movers JCT', 'location' => 'JCT', 'allocation_2026_original' => '65', 'allocation_2026_revised' => '0', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '650', 'phys_percent' => ['Q1' => '10%', 'Q1_Target' => '10%', 'Q1_Cum_Target' => '10%', 'Q1_Cum_Prog' => '10%', 'Q1_Overall_Prog_Final' => '10%'], 'actual_exp' => ['Q1' => '400'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '32-MECH', 'institution' => 'SLPA', 'category' => 'Continuation', 'division' => 'Mechanical', 'project_name' => 'Road Sweeper JCT', 'location' => 'JCT', 'allocation_2026_original' => '6000', 'allocation_2026_revised' => '0', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '600', 'phys_percent' => ['Q1' => '0%', 'Q1_Target' => '10%', 'Q1_Cum_Target' => '10%', 'Q1_Cum_Prog' => '0%', 'Q1_Overall_Prog_Final' => '0%'], 'actual_exp' => ['Q1' => '800'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '10-MECH-NEW', 'institution' => 'SLPA', 'category' => 'New', 'division' => 'Mechanical', 'project_name' => '10 Ton Forklift BQ', 'location' => 'BQ', 'allocation_2026_original' => '800', 'allocation_2026_revised' => '0', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '800', 'phys_percent' => ['Q1' => '15%', 'Q1_Target' => '0%', 'Q1_Cum_Target' => '0%', 'Q1_Cum_Prog' => '15%', 'Q1_Overall_Prog_Final' => '15%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '11-MECH-NEW', 'institution' => 'SLPA', 'category' => 'New', 'division' => 'Mechanical', 'project_name' => '15 Ton Forklift BQ', 'location' => 'BQ', 'allocation_2026_original' => '1100', 'allocation_2026_revised' => '0', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '110', 'phys_percent' => ['Q1' => '15%', 'Q1_Target' => '0%', 'Q1_Cum_Target' => '0%', 'Q1_Cum_Prog' => '15%', 'Q1_Overall_Prog_Final' => '15%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '12-MECH-NEW', 'institution' => 'SLPA', 'category' => 'New', 'division' => 'Mechanical', 'project_name' => '20 Ton Forklift BQ', 'location' => 'BQ', 'allocation_2026_original' => '2200', 'allocation_2026_revised' => '0', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '2200', 'phys_percent' => ['Q1' => '15%', 'Q1_Target' => '0%', 'Q1_Cum_Target' => '0%', 'Q1_Cum_Prog' => '15%', 'Q1_Overall_Prog_Final' => '15%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '13-MECH-NEW', 'institution' => 'SLPA', 'category' => 'New', 'division' => 'Mechanical', 'project_name' => 'Over Height Spreaders ECT', 'location' => 'ECT', 'allocation_2026_original' => '800', 'allocation_2026_revised' => '0', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '80', 'phys_percent' => ['Q1' => '15%', 'Q1_Target' => '0%', 'Q1_Cum_Target' => '0%', 'Q1_Cum_Prog' => '15%', 'Q1_Overall_Prog_Final' => '15%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track'],

                    // --- 9. IS (3 Projects) ---
                    ['serial_no' => '35-IS', 'institution' => 'SLPA', 'category' => 'Continuation', 'division' => 'IS', 'project_name' => 'Terminal Management System Semi ECT', 'location' => 'ECT', 'allocation_2026_original' => '40', 'allocation_2026_revised' => '39.06', 'cum_exp_2025' => '2696', 'cum_phys_2025' => '90%', 'q1_fin_target' => '6594', 'phys_percent' => ['Q1' => '100%', 'Q1_Target' => '100%', 'Q1_Cum_Target' => '10%', 'Q1_Cum_Prog' => '100%', 'Q1_Overall_Prog_Final' => '10%'], 'actual_exp' => ['Q1' => '150'], 'timeline_status' => 'Delayed'],
                    ['serial_no' => '36-IS', 'institution' => 'SLPA', 'category' => 'Continuation', 'division' => 'IS', 'project_name' => 'Port Community System', 'location' => 'Colombo', 'allocation_2026_original' => '0', 'allocation_2026_revised' => '0', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '0%', 'Q1_Target' => '100%', 'Q1_Cum_Target' => '10%', 'Q1_Cum_Prog' => '0%', 'Q1_Overall_Prog_Final' => '10%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'Delayed'],
                    ['serial_no' => '14-IS', 'institution' => 'SLPA', 'category' => 'New', 'division' => 'IS', 'project_name' => 'ERP Solution for CECT', 'location' => 'SLPA', 'allocation_2026_original' => '160', 'allocation_2026_revised' => '0', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '4000', 'phys_percent' => ['Q1' => '0%', 'Q1_Target' => '0%', 'Q1_Cum_Target' => '0%', 'Q1_Cum_Prog' => '0%', 'Q1_Overall_Prog_Final' => '0%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'Terminated'],

                    // --- 10. SECURITY (1 Project) ---
                    ['serial_no' => '37-SEC', 'institution' => 'SLPA', 'category' => 'Continuation', 'division' => 'Security', 'project_name' => 'CCTV Camera System and Gates Control', 'location' => 'Colombo', 'allocation_2026_original' => '143', 'allocation_2026_revised' => '145', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '145', 'phys_percent' => ['Q1' => '10%', 'Q1_Target' => '10%', 'Q1_Cum_Target' => '0.01%', 'Q1_Cum_Prog' => '10%', 'Q1_Overall_Prog_Final' => '10%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track']
                ]
            ],
            'MSS' => [
                'institution_name' => 'Merchant Shipping Secretariat',
                'projects' => [
                    // --- MSS PROJECTS ---
                    ['serial_no' => '1', 'project_cord' => 'MSS-01', 'institution' => 'MSS', 'category' => 'Continuation', 'division' => 'E-Government', 'project_name' => 'Establishment of E-Government project integrating all services of the merchant shipping secretariat', 'location' => 'Colombo', 'allocation_2026_original' => '20', 'allocation_2026_revised' => '0', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '0%', 'Q1_Target' => '15.00%', 'Q1_Cum_Target' => '15.00%', 'Q1_Cum_Prog' => '0%', 'Q1_Quarterly_Cum' => '0%', 'Q1_Overall_Prog_Final' => '0%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'Delayed']
                ]
            ]
        ],
        'jct' => [
            'JCT' => [
                'institution_name' => 'Jaya Container Terminals Limited',
                'projects' => [
                    ['serial_no' => '1', 'project_cord' => 'JCT-E01', 'institution' => 'JCT', 'category' => 'Extension', 'division' => 'JCT', 'project_name' => 'Install smoke detectors in Boiler, Generator, and Engine Rooms', 'location' => 'JCT Ltd', 'allocation_2026_original' => '2.50', 'allocation_2026_revised' => '2.50', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '0%', 'Q1_Target' => '0%', 'Q1_Cum_Target' => '0%', 'Q1_Cum_Prog' => '0%', 'Q1_Quarterly_Cum' => '0%', 'Q1_Overall_Prog_Final' => '0%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track'],
                    ['serial_no' => '2', 'project_cord' => 'JCT-N02', 'institution' => 'JCT', 'category' => 'New', 'division' => 'JCT', 'project_name' => 'Fabrication of 01 Nos of 12000MT Capacity fuel storage Tank', 'location' => 'JCT Ltd', 'allocation_2026_original' => '940', 'allocation_2026_revised' => '940', 'cum_exp_2025' => '0', 'cum_phys_2025' => '0%', 'q1_fin_target' => '0', 'phys_percent' => ['Q1' => '0%', 'Q1_Target' => '5%', 'Q1_Cum_Target' => '5%', 'Q1_Cum_Prog' => '0%', 'Q1_Quarterly_Cum' => '0%', 'Q1_Overall_Prog_Final' => '0%'], 'actual_exp' => ['Q1' => '0'], 'timeline_status' => 'On Track'],
                ]
            ]
        ]
    ]
];